spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: hotel
    password: hotel
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
